### ISSUE TITLE
internal/fixturegen: TestFixtureCoverage red on main — github_resolution_cache has no fixture row

### ISSUE THREAD

**Issue by ptone** [ptone/scion#625]
## Summary

`TestFixtureCoverage` **fails on `main`** (`b03a09ac`). It is not a regression from any in-flight branch — I confirmed it reproduces byte-identically on a clean `main` worktree.

```
$ go test ./internal/fixturegen/... -run TestFixtureCoverage
    fixturegen_test.go:48: Error: Not equal:
                expected: 42
                actual  : 43
                Messages: fixture should cover exactly the 42 domain tables
    fixturegen_test.go:50: Error: Should be empty, but was [github_resolution_cache]
                Messages: every domain table must have at least one fixture row; missing: [github_resolution_cache]
FAIL	github.com/GoogleCloudPlatform/scion/internal/fixturegen	0.120s
```

## Mechanism

The `github_resolution_cache` ent table was added without a corresponding fixture row or a bump to the expected-count constant.

- Table: `pkg/ent/schema/github_resolution_cache.go`, registered at `pkg/ent/migrate/schema.go:281-295`
- Consumer: `pkg/hub/github_resolution_store.go`
- Introduced by #885 (`13db0104`, broker-singleton GitHub skill resolution cache), still uncovered as of #900 (`6c66b66d`)

The gate itself is working exactly as designed — `internal/fixturegen/fixturegen_test.go:33` documents `expectedTableCount` as *"the number of domain tables in the hub schema … The fixture must cover every one of them."* The schema grew to 43 and neither the fixture nor the constant followed.

## Fix

Two parts, and **both are needed** — bumping the constant alone would satisfy the first assertion while leaving `report.Missing` non-empty:

1. Add a `github_resolution_cache` fixture row in `internal/fixturegen/spec.go`.
2. Bump `expectedTableCount` from 42 to 43 in `internal/fixturegen/fixturegen_test.go:33`.

## Why this is worth filing rather than fixing in passing

Any whole-repo `go test ./...` is red on `main` today. That is corrosive in a specific way: it trains people to expect a failure in this package and to skim past it, which is precisely how the *next* uncovered table gets missed. The gate only works if it is green.

Found by `sp-dev4` during a full-repo run on the settings-precedence workstream, which correctly flagged it as not its own. Deliberately **not** fixed inside that PR — unrelated to settings precedence, and the PR already spans eleven phases.

**Comment by ptone** [comment]
**Freshness review (2026-08-29):**
Status: Still valid
Recommendation: Promote to Next
Evidence: Confirmed the test still fails on the current tree. `go test -count=1 -run TestFixtureCoverage ./internal/fixturegen/...` produces: `expected: 42, actual: 43` and `missing: [github_resolution_cache]`. The constant at `internal/fixturegen/fixturegen_test.go:34` is still `42`. The `github_resolution_cache` schema exists at `pkg/ent/schema/github_resolution_cache.go` and is registered in `pkg/ent/migrate/schema.go`, but no fixture row exists in `internal/fixturegen/`. This is a two-line fix (bump constant to 43, add fixture row in `spec.go`) that is blocking any clean `go test ./...` run on main. Since it undermines the test gate's value and trains developers to ignore failures in this package, promoting to Next is warranted.
